### PR TITLE
Only extract ffmpeg and ffprobe from the tarball

### PR DESCRIPTION
**Pull request by sodabrew**
Avoid leaving behind the expanded tarball contents by grabbing just the ffmpeg and ffprobe files.

### CODE REVIEW

**Comment by sodabrew** [comment]
```
root@dd8219a04d44:/coach# ls -l /
total 51644
drwxr-xr-x   2 root root     4096 May  9 13:54 bin
drwxr-xr-x   2 root root     4096 Apr 24 08:34 boot
drwxr-xr-x   2 root root     4096 May 12 11:20 coach
drwxr-xr-x   5 root root      360 May 12 11:25 dev
drwxr-xr-x  67 root root     4096 May 12 11:25 etc
drwxr-xr-x   3 1000 1000     4096 May  9 10:54 ffmpeg-4.0-64bit-static
-rw-r--r--   1 root root 52805308 May  7 23:49 firefox-61.0b3.tar.bz2
drwxr-xr-x   2 root root     4096 Apr 24 08:34 home
drwxr-xr-x  14 root root     4096 May  9 13:56 lib
drwxr-xr-x   2 root root     4096 Apr 26 21:16 lib64
drwxr-xr-x   2 root root     4096 Apr 26 21:16 media
drwxr-xr-x   2 root root     4096 Apr 26 21:16 mnt
drwxr-xr-x   4 root root     4096 May  9 13:55 opt
dr-xr-xr-x 162 root root        0 May 12 11:25 proc
drwx------   6 root root     4096 May 12 11:20 root
drwxr-xr-x   5 root root     4096 Apr 27 23:28 run
drwxr-xr-x   2 root root     4096 May  9 13:53 sbin
drwxr-xr-x   2 root root     4096 Apr 26 21:16 srv
-rwxr-xr-x   1 root root      614 May 12 11:00 start.sh
dr-xr-xr-x  13 root root        0 May 12 11:25 sys
drwxrwxrwt   4 root root     4096 May  9 13:56 tmp
drwxr-xr-x  33 root root     4096 May 12 11:20 usr
drwxr-xr-x  22 root root     4096 May  9 13:52 var
```

Not needed:
```
drwxr-xr-x   3 1000 1000     4096 May  9 10:54 ffmpeg-4.0-64bit-static

root@dd8219a04d44:/coach# du -sh /ffmpeg*
68M	/ffmpeg-4.0-64bit-static
```

Similar fix as https://github.com/sitespeedio/docker-browsers/pull/1 but in this case I'm avoiding extracting the full tarball.

Alternatively, changing line `rm ffmpeg-release-64bit-static.tar.xz && \` to `rm -r ffmpeg-* && \` would work as well to zap the extracted directory along with the tarball.

**Comment by soulgalore** [comment]
thanks again @sodabrew !

**Comment by sodabrew** [comment]
Oops, I missed the `—wildcards` flag :facepalm:

**Comment by soulgalore** [comment]
Np, that happens everyone :) Thanks for the fixes @sodabrew the total sized decreased a lot!

**Pull request merged**
